music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /music/album_id/
    url(r'^(?P<pk>[0-9]+)\\$', views.DetailView.as_view(), name="detail"),

    # /music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    # /details
    # url(r'^$', views.IndexView.as_view(), name='index'),

]

websites/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),

]

music/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse


# Red pk 1
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title + ' _ ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Album


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()
        return render_to_response(template='index.html')

class DetailView(generic.DetailView):
    model = Album
    template_name ='details/index.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

music/templates/details/index.html
{% extends 'index.html' %}
{% block title %}Album Details{% endblock %}

{% block body %}

        <img src="{{ album.album_logo}}" style="width:250px;">

        <h1>{{ album.album_title }}</h1>
        <h2>{{ album.artist }}</h2>

        {% for song in album.song_set.all %}
            {{ song.song_title }}
            {% if song.isfavorite %}
                <img src="https://www.google.com/imgres?imgurl=https%3A%2F%2Fstatic1.squarespace.com%2Fstatic%2F553a8716e4b0bada3c80ca6b%2F553a9655e4b03939abece18a%2F5731fc75f85082142b12b095%2F1471894315703%2Fmayfourblocknature.jpg&imgrefurl=http%3A%2F%2Fwww.sciencesource.com%2F&docid=Tw-7xVolhcYqKM&tbnid=f8x-MKrxVWP_bM%3A&vet=1&w=500&h=286&bih=683&biw=1292&ved=0ahUKEwj24MLL977QAhVKIsAKHYAfC08QMwhBKBAwEA&iact=mrc&uact=8"/>
            {% endif %}
            <br>
        {% endfor %}

{% endblock %}

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container fluid">

    <div class="row">
        <div class="col-sm-12 col-md-/">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="post" enctype="multi part/form-data/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit"class="btn btn-success">Submit</button>
                            </div>

                        </div>


                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>None</title>
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
     <nav class="navbar navbar-inverse">
     <div class="container-fluid">

      <!  Header >
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#topNavBar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            <a class ="navbar-brand" href="{% url 'music:index' %}">me</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav pull-left">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                    </a>
                </li>
                <li class="">
                    <form class="navbar-form navbar-right" role="search" method="get" action="">
                      <div class="form-group">
                        <input type="text" class="form-control"  name="q" value="">
                      </div>
                      <button type="submit" class="btn btn-default">Search</button>
                    </form>
                </li>
            </ul>

            <ul class="nav navbar-nav pull-right">


                <li class="nav navbar-right">
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li class="nav navbar-right">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>

            </ul>
            <div class="clearfix"></div>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}

{% block body %}

        <img src="{{ album.album_logo}}" style="width:250px;">

        <h1>{{ album.album_title }}</h1>
        <h2>{{ album.artist }}</h2>

        {% for song in album.song_set.all %}
            {{ song.song_title }}
            {% if song.isfavorite %}
                <img src="https://www.google.com/imgres?imgurl=https%3A%2F%2Fstatic1.squarespace.com%2Fstatic%2F553a8716e4b0bada3c80ca6b%2F553a9655e4b03939abece18a%2F5731fc75f85082142b12b095%2F1471894315703%2Fmayfourblocknature.jpg&imgrefurl=http%3A%2F%2Fwww.sciencesource.com%2F&docid=Tw-7xVolhcYqKM&tbnid=f8x-MKrxVWP_bM%3A&vet=1&w=500&h=286&bih=683&biw=1292&ved=0ahUKEwj24MLL977QAhVKIsAKHYAfC08QMwhBKBAwEA&iact=mrc&uact=8"/>
            {% endif %}
            <br>
        {% endfor %}

{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
       <div class="col-sm-offset-2 col-sm-10">
           <span class="text-danger small">{{ field.errors }}</span>
       </div>
       <label class="control-label col-sm-2">{{ field.label_tag }}</label>
       <div class="control-label col-sm-2">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}

        <ul>
            {% for album in all_albums %}
            <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
            {% endfor %}
        </ul>

{% endblock %}